package ru.cherepanov.test.task.dynamica.exception;

public class ValidationFailedException extends RuntimeException{
}
